### ISSUE TITLE
 Syntax error on line 13 index.py (inbound DNS lambda function)

### ISSUE THREAD

**Issue by mightymouse2045** [aws-samples/dns-using-service-catalog-and-control-tower-customizations#1]
Hi as per the code there is a syntax error. Fixing that then gives another error. Something is not right and the inbound DNS product does not deploy properly with the code in Route53-DNS-Service-Catalog-Hub-Account.yml, following excerpt:

```
          # Import statements
          import boto3
          import json
          from botocore.exceptions import ClientError
          # Start Lambda function
          def lambda_handler(event, context):
            route53 = boto3.client('route53')
            print(f"Hosted Zone {event['Records'][0]['Sns']['Subject']}")
            associationData = json.loads(event['Records'][0]['Sns']['Message'])
            print('data received:', associationData)
            try: 
              response = route53.create_vpc_association_authorization(
                  HostedZoneId = associationData['hostedZoneId']},  <<<<< missing {
                  VPC={
                    "VPCRegion": associationData['VPCRegion'],
                    "VPCId": associationData['VPCId']
                  }
                )
              print(response)
              print("Respond: SUCCESS")
              return
            except ClientError as ex:
              print('Creating hosted zone authorization has failed.  See the following error.')
              print(ex.response['Error']['Message'])
              print("Respond: FAILED")
              return
```

The line is missing a { and when I fix this it then complains of:

```
'set' object has no attribute 'split': AttributeError
Traceback (most recent call last):
  File "/var/task/index.py", line 16, in lambda_handler
    "VPCId": associationData['VPCId']
  File "/var/runtime/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 678, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/var/runtime/botocore/client.py", line 724, in _convert_to_request_dict
    api_params, operation_model, context)
  File "/var/runtime/botocore/client.py", line 756, in _emit_api_params
    params=api_params, model=operation_model, context=context)
  File "/var/runtime/botocore/hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/var/runtime/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/var/runtime/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/var/runtime/botocore/handlers.py", line 587, in fix_route53_ids
    params[name] = orig_value.split('/')[-1]
AttributeError: 'set' object has no attribute 'split'

```

**Comment by mightymouse2045** [comment]
> Hi as per the code there is a syntax error. Fixing that then gives another error. Something is not right and the inbound DNS product does not deploy properly with the code in Route53-DNS-Service-Catalog-Hub-Account.yml, following excerpt:
> 
> ```
>           # Import statements
>           import boto3
>           import json
>           from botocore.exceptions import ClientError
>           # Start Lambda function
>           def lambda_handler(event, context):
>             route53 = boto3.client('route53')
>             print(f"Hosted Zone {event['Records'][0]['Sns']['Subject']}")
>             associationData = json.loads(event['Records'][0]['Sns']['Message'])
>             print('data received:', associationData)
>             try: 
>               response = route53.create_vpc_association_authorization(
>                   HostedZoneId = associationData['hostedZoneId']},  <<<<< missing {
>                   VPC={
>                     "VPCRegion": associationData['VPCRegion'],
>                     "VPCId": associationData['VPCId']
>                   }
>                 )
>               print(response)
>               print("Respond: SUCCESS")
>               return
>             except ClientError as ex:
>               print('Creating hosted zone authorization has failed.  See the following error.')
>               print(ex.response['Error']['Message'])
>               print("Respond: FAILED")
>               return
> ```
> 
> The line is missing a { and when I fix this it then complains of:
> 
> ```
> 'set' object has no attribute 'split': AttributeError
> Traceback (most recent call last):
>   File "/var/task/index.py", line 16, in lambda_handler
>     "VPCId": associationData['VPCId']
>   File "/var/runtime/botocore/client.py", line 386, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>   File "/var/runtime/botocore/client.py", line 678, in _make_api_call
>     api_params, operation_model, context=request_context)
>   File "/var/runtime/botocore/client.py", line 724, in _convert_to_request_dict
>     api_params, operation_model, context)
>   File "/var/runtime/botocore/client.py", line 756, in _emit_api_params
>     params=api_params, model=operation_model, context=context)
>   File "/var/runtime/botocore/hooks.py", line 357, in emit
>     return self._emitter.emit(aliased_event_name, **kwargs)
>   File "/var/runtime/botocore/hooks.py", line 228, in emit
>     return self._emit(event_name, kwargs)
>   File "/var/runtime/botocore/hooks.py", line 211, in _emit
>     response = handler(**kwargs)
>   File "/var/runtime/botocore/handlers.py", line 587, in fix_route53_ids
>     params[name] = orig_value.split('/')[-1]
> AttributeError: 'set' object has no attribute 'split'
> ```

Actually the fix is to adjust line 13 as:

```
                  HostedZoneId = associationData['hostedZoneId'],
```

Just delete } and it works
